# fly.toml app configuration file generated for winter-dew-2449 on 2023-11-02T15:58:53+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-dew-2449"
primary_region = "syd"

[experimental]
  cmd = ["startup.sh"]
  entrypoint = ["sh"]

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
